[package]
name = "mdbook-plantuml"
version = "0.7.0"
authors = ["Sytse Reitsma <mdbook-plantuml@sreitsma.nl>"]
description = "A preprocessor for mdbook which will convert plantuml code blocks into inline SVG diagrams"
license = "MIT"
documentation = "https://docs.rs/mdbook-plantuml"
repository = "https://github.com/sytsereitsma/mdbook-plantuml"
readme = "README.md"
keywords = ["mdbook", "plantuml", "markdown", "commonmark"]
exclude = [
    "tests/e2etest",
]
edition = "2018"

[[bin]]
name = "mdbook-plantuml"
path = "src/bin/mdbook-plantuml.rs"
doc = false

[features]
default = ["plantuml-ssl-server"]
plantuml-server=["reqwest", "deflate"]
plantuml-ssl-server=["reqwest/default-tls", "deflate"]

[dependencies]
mdbook = { version = "0.4.10", default-features = false }
#mdbook = { path = "../mdBook", default-features = false }
serde = "1.0.126"
serde_json = "1.0.64"
log = "0.4.14"
env_logger = "0.8.4"
failure = "0.1.8"
serde_derive = "1.0.126"
failure_derive = "0.1.8"
clap = "2.33.3"
log4rs = "1.0.0"
reqwest = {version = "0.11.3", optional = true, features = ["blocking"], default-features = false}
deflate = { version = "0.9.1", optional = true }
sha1 = { version = "0.6.0", features = ["std"] }
tempfile = "3.2.0"
futures = "0.3.15"

[dev-dependencies]
pretty_assertions = "0.7.2"
simulacrum = "0.3.1"
